### ISSUE TITLE
exp-10: create a HTML form with validation using vanilla JS

### ISSUE THREAD

**Issue by chankruze** [chankruze/iwt-lab#4]
**Objectives:**
- [ ] Create a from element with with `get` method and no action
- [ ] Add a `div` for showing for validation error
  - [ ] username:
    - [ ] allow user to submit with empty username and render error message if the field is empty (don't use `required` attribute in `input`)
    - [ ] can't contain special character except `_`
  - [ ] password: 
    - [ ] use `required` html attribute in `input`
    - [ ] must be at least 8 character long
- [ ] If all checks are passing, log the username and hashed password and store the username in cookies with expiry time T+15 minutes.

**Comment by Bib3k4u** [comment]
Is it open?
Can I work on it?

**Comment by chankruze** [comment]
Yes you can work ;)

**Comment by Bib3k4u** [comment]
I'm working on it. Can you please add hacktoberfest-accepted label on it?

**Comment by chankruze** [comment]
> I'm working on it. Can you please add hacktoberfest-accepted label on it?

Hacktobefest accepted label is needed in the repo topics not on the Issues.

Focus on your work, your PR will be counted.

**Comment by Bib3k4u** [comment]
hey, @chankruze I have raised the PR Please have a Look into it.
