### ISSUE TITLE
exp-11: build a notes web app with vanilla JS and local storage

### ISSUE THREAD

**Issue by chankruze** [chankruze/iwt-lab#5]
The UI should look like this

![image](https://github.com/chankruze/iwt-lab/assets/29806845/5be06ea2-7965-4e61-93ec-e02e853ca2d5)

**Objectives:**
- [ ] This should be a single page app (no navigation).
- [ ] List the title and max lines of content with last edited date in left notes list.
- [ ] Clicking on a note card on left list will open the whole note on right portion of the screen.
- [ ] Make the left section and right section scrollable independently on overflow content. Which means if there are a lots of notes in the list, only left section should be scrollable. If the content of a note is huge (overflowing the viewport) only then the right section should be scrollable.
- [ ] Show delete option when a note is opened in the right section.

**Comment by abdulbari149** [comment]
Hey, I would like to work on this.

**Comment by Bib3k4u** [comment]
I would work on this if you add the label hacktoberfest-accepted.

**Comment by chankruze** [comment]
> I would work on this if you add the label hacktoberfest-accepted.

Assigned ;)

**Comment by Bib3k4u** [comment]
Created the App
exp-11: build a notes web app with vanilla JS and local storage #5
Done
![Screenshot 2023-10-13 012339](https://github.com/chankruze/iwt-lab/assets/106904143/66fb2dfd-e1b9-4026-9195-fd4603b5884d)
