### ISSUE TITLE
exp-12: create an random quote generator web app

### ISSUE THREAD

**Issue by chankruze** [chankruze/iwt-lab#7]
Implement this figma design: https://www.figma.com/file/JS7wXHPdmtkXQCRdLVDqwf/Untitled?type=design&node-id=1%3A2&mode=design&t=VLqdgLx3sT5IoCjK-1

**_Note:_**

- The quotes should be fetched from any free API.
- The refresh button should load a new quote from API when clicked.
- The UI should be responsive for both mobile and desktop devices.
- The quote should be in the middle of the screen.
- Maintain proper whitespacing (padding and margin etc.).

![image](https://github.com/chankruze/iwt-lab/assets/29806845/f74e6973-57bb-42aa-9c25-a9bdea0ad2bb)

**Comment by sidhartha2002** [comment]
### **Hey Bro, plz assign me the issue. I m interested.**
